### ISSUE TITLE
program day name starting by a number

### ISSUE THREAD

**Issue by ricardomar** [piazzai/jekyll-nagymaros#2]
Hi everyone,

I've noticed an issue with the current implementation: it seems to encounter bugs when the day name begins with a number. For instance:

17 Julho
18 Julho

Navigation across different days fails as a result.

**Comment by piazzai** [comment]
Thank you for catching it. It is fixed in 2.0.1. Make sure to load the latest version of the gem and let me know if there is any further issue.

**Comment by ricardomar** [comment]
thank you
