### ISSUE TITLE
Broken demo link in README.md

### ISSUE THREAD

**Issue by linkclau** [piazzai/jekyll-nagymaros#5]
The demo link in README.md points to https://jekyll-nagymaros.netlify.app/ which doesn't seem to be active.
https://piazzai.github.io/jekyll-nagymaros/ is probably the correct link

There should also be a related pull request.

(sorry for my GitHub mess up :-()

**Comment by piazzai** [comment]
That's correct. I migrated the demo site and forgot to update the link. Merged in #4.
