### ISSUE TITLE
Program Days Menu - Not Collapsing Properly on Small Screens

### ISSUE THREAD

**Issue by ricardomar** [piazzai/jekyll-nagymaros#6]
Hi all,

In the program section, the list of days for programs lasting more than 4 days works well on medium and large screens. However, on small screens, the list does not collapse into two or more rows. Instead, it collapses into a single row that extends beyond the screen size.

print screens attached to this issue report.
![large-screen](https://github.com/piazzai/jekyll-nagymaros/assets/4249828/5d92a43e-7240-4633-87be-2daa91e26ebf)
![small-screen-01](https://github.com/piazzai/jekyll-nagymaros/assets/4249828/09d05fbb-2c0c-4188-8245-4775dc5bca65)
![small-screen-02](https://github.com/piazzai/jekyll-nagymaros/assets/4249828/a4603483-5461-45b8-9ec3-7aa504f4d26e)

You can see a live example here (please note that it may change in the coming days):
https://cibit-uc.github.io/summerschool/programa/

thank you.

best regards,
Ricardo Martins

**Comment by piazzai** [comment]
Hi Ricardo. I was aware of this problem and planned to fix it later this year as part of a broader restyling of the theme. But to solve it right now, I quickly pushed an update that introduces a new layout for the program page. In this new layout, the issue will not occur.

Please load the latest version of the gem, v2.2.0. Then rebuild the side, check the program page and see if all works well.

**Comment by ricardomar** [comment]
thank you :)
